blueprint:
  name: Intelligent Plant Care Monitor
  description: v1.0.0 – Configurable alert time + light duration tracking
  domain: automation
  input:
    plant_type:
    name: Plant Type
    description: Select the plant type
    selector:
      select:
        options:
        - Chili
        - Citrus
        - Ficus
  growth_stage:
    name: Growth Stage
    description: Select the growth stage
    selector:
      select:
        options:
        - Cutting
        - Dormant
        - Fruiting
        - Mature
        - Seed
        - Sprout
        - Young

    lux_sensor:
      name: Light Intensity Sensor
      selector:
        entity:
          domain: sensor
    awc_sensor:
      name: Soil Moisture Sensor (AWC)
      selector:
        entity:
          domain: sensor
    temperature_sensor:
      name: Temperature Sensor
      selector:
        entity:
          domain: sensor
    humidity_sensor:
      name: Humidity Sensor
      selector:
        entity:
          domain: sensor
    input:
    notify_target:
      name: Notify Target
      description: Select the notification service to use
      default: notify.notify
      selector:
        text:

    alert_time:
      name: Daily Alert Time (HH:MM:SS)
      default: "18:00:00"
      selector:
        time:

 
trigger:
  - platform: time_pattern
    minutes: "/15"
  - platform: time
    at: !input alert_time
