- platform: history_stats
  name: Light Duration Last 24h
  entity_id: binary_sensor.light_active
  state: "on"
  type: time
  start: "{{ now() - timedelta(hours=24) }}"
  end: "{{ now() }}"

- platform: file
  name: Plant Data
  file_path: /config/plant_care/plantdata.json
  scan_interval: 3600

- platform: template
  sensors:
    plantcare_status:
      friendly_name: "Plant Care Status"
      value_template: >
        {% set alert = states('input_text.plant_alert_text') %}
        {{ alert if alert else '✅ All parameters are optimal' }}
